version: "3.8"

services:
  mage:
    image: mageai/mageai:latest
    container_name: mage
    ports:
      - "6789:6789"
    volumes:
      - ./mage_homework_03:/home/src
    environment:
      - USER_CODE_PATH=/home/src
    networks:
      - app-network

  mlflow:
    build:
      context: .
      dockerfile: mlflow.dockerfile
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/home/mlflow
    networks:
      - app-network

networks:
  app-network:
