version: '3.8'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEBUG=1
    ports:
      - "4566:4566"
    volumes:
      - "./localstack:/tmp/localstack/data"
    networks:
      - localstack-net

networks:
  localstack-net:
    driver: bridge